#  Name of workflow
name: Production workflow

# When workflow is triggered
on:
  push:
    branches: [main]

# Jobs to carry out
jobs:
  deploy:
    # Operating system to run job on
    runs-on: ubuntu-latest
    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v1
      # Install NodeJS
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3.7.1
        with:
          github-token: ${{ secrets.github_token }}

      - name: create release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}

      # Run npm install and build on our code
      - name: Build the Application
        run: npm install
        run: npm run build --if-present

      # Deploy to Netlify using our build hook, but only if tests pass
      - name: Deploy to netlify
        if: success()
        run: curl -X POST -d {}  ${{ secrets.NETLIFY_BUILD_HOOK_PROD }}