#  Name of workflow
name: Production workflow

# When workflow is triggered
on:
  push:
    branches: [master]

# Jobs to carry out
jobs:
  deploy:
    # Operating system to run job on
    runs-on: ubuntu-latest
    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v1
      # Install NodeJS
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install Dependencies
        run: npm install

      - name: Set Git user name and email
        env:
          GIT_AUTHOR_NAME: ${{ secrets.AUTHOR_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.AUTHOR_EMAIL }}
          GIT_ORIGIN: ${{secrets.REMOTE}}
        run: git config --global user.name "${GIT_AUTHOR_NAME}"
      - run: git config --global user.email "${GIT_AUTHOR_EMAIL}"

      - name: Create a release
        run: git checkout master
      - run: npm run release

      - name: Publish the releases
        run: git push --follow-tags ${GIT_ORIGIN} HEAD:master

      # Run npm install and build on our code
      - name: Build the Application
        run: npm run build --if-present

      # Deploy to Netlify using our build hook, but only if tests pass
      - name: Deploy to netlify
        if: success()
        run: curl -X POST -d {}  ${{ secrets.NETLIFY_BUILD_HOOK_PROD }}